[tool.poetry]
name = "diffvg"
version = "0.1.0"
description = ""
authors = ["Marco Lee <marco@goodnotesapp.com>"]

[tool.poetry.dependencies]
python = ">=3.11"
pygame = "^2.0.1"
torch = "^2.2.0"
torchvision = "^0.17.0"
numba = "^0.59.0"
matplotlib = "^3.8.3"

[tool.poetry.dev-dependencies]
scikit-image = "^0.19.3"
svgwrite = "^1.4.1"
svgpathtools = "^1.4.1"
cssutils = "^2.2.0"
visdom = "^0.1.8"
cmake = "^3.18.4"

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"
